### ISSUE TITLE
GLIBC_2.32 and GLIBC_2.33' not found (required by clang)

### ISSUE THREAD

**Issue by TogoFire** [Panchajanya1999/azure-clang#1]
Log:
https://hastebin.com/zedagoruqi.apache

togofire@togofire:~$ cat /etc/os-release
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal
togofire@togofire:~$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; read the sources for copy conditions. THERE IS NOT
ANY WARRANTY; nor for MERCHANTABILITY or FITNESS TO ANY
PURPOSE IN PARTICULAR.
Written by Roland McGrath and Ulrich Drepper.

**Comment by Panchajanya1999** [comment]
You should see that it's been deprecated. Instead, use the one in gitlab. 

Oh, if u see glibc error, upgrade your distro. 
[Edited]

Don't force upgrade glibc on debian systems. U will break your distro.

**Comment by TogoFire** [comment]
Yes, I'm using the current one from gitlab.
And yes it's true debian/ubuntu doesn't mind updating glibc, and trying manually will break the system.

The problem really is that I use a rented (shared) + Jenkis server to compile, and it comes with the damn ubuntu, ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27.

And it's really annoying having to migrate to archlinux or fedora to be able to use this.
